{
 "title": "SmartMeter Vienna",
 "description": "SmartMeter of WienerNetze",
 "tags": [
  "smartmeter",
  "wiener netze",
  "smartmetervienna",
  "vienna",
  "iot",
  "power",
  "consumption"
 ],
 "time": { "from": "now-8d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "influxdb bucket", "query": "smartmetervienna" },
   { "name": "measurement", "label": "influxdb measurement", "query": "Consumption_15min_Wh" }
  ]
 },
 "panels": [
  {
   "title": "Tag (letzter)",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 56 }
   ]
  },
  {
   "title": "Tag (max.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 56 }
   ]
  },
  {
   "title": "Tag (min.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 56 }
   ]
  },
  {
   "title": "Tag (avg.)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 56 }
   ]
  },
  {
   "title": "Last (15min)",
   "type": "timeseries",
   "description": "Durchschnittliche Last in Watt je Viertelstunde",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Vienna\")\r\n\r\nbucket = ${bucket:doublequote}\r\nmeasurement = ${measurement:doublequote}\r\n\r\nfrom(bucket: bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == measurement)\r\n|> keep(columns: [\"_value\", \"_time\"])\r\n|> map(fn: (r) => ({ r with _value: float(v: r._value) * 4.0}))"
    }
   ]
  },
  {
   "title": "Verbrauch (15min)",
   "type": "timeseries",
   "description": "Verbrauch in Wattstunden je Viertelstunde",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Vienna\")\r\n\r\nbucket = ${bucket:doublequote}\r\nmeasurement = ${measurement:doublequote}\r\n\r\nfrom(bucket: bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == measurement)\r\n|> keep(columns: [\"_value\", \"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Verbrauch (1h)",
   "type": "timeseries",
   "description": "Verbrauch in Wattstunden je Stunde",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Vienna\")\r\n\r\nbucket = ${bucket:doublequote}\r\nmeasurement = ${measurement:doublequote}\r\n\r\nfrom(bucket: bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == measurement)\r\n|> keep(columns: [\"_value\", \"_time\"])\r\n|> aggregateWindow(fn: sum, every: 1h)\r\n|> timeShift(duration:-1h)"
    }
   ]
  },
  {
   "title": "Verbrauch (1 Tag)",
   "type": "timeseries",
   "description": "Verbrauch in Wattstunden je Tag",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Vienna\")\r\n\r\nbucket = ${bucket:doublequote}\r\nmeasurement = ${measurement:doublequote}\r\n\r\nfrom(bucket: bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == measurement)\r\n|> keep(columns: [\"_value\", \"_time\"])\r\n|> aggregateWindow(fn: sum, every: 1d)\r\n|> timeShift(duration:-1d)"
    }
   ]
  }
 ]
}